### ISSUE TITLE
Extension Updater wont detect extensions installed into roaming

### ISSUE THREAD

**Issue by spektor56** [erri120/Playnite.Extensions#17]
Playnite installation has 2 folders:

C:\Users\l-bre\AppData\Roaming\Playnite\Extensions
and 
C:\Users\l-bre\AppData\Local\Playnite\Extensions

Playnite installs PEXT extensions into C:\Users\l-bre\AppData\Roaming\Playnite\Extensions and the extension updater isn't detecting my extensions there.

**Comment by erri120** [comment]
Should be fixed in b6485db3345e0203075c05463b18fbc7cd36bd9d . The updater uses the Playnite Paths API to check for the `Extensions` folder inside the application and config folder. The config folder is in `%appdata%` so PEXT extensions can also be found.
