### ISSUE TITLE
F95ZoneMetadata fails to detect community score.

### ISSUE THREAD

**Issue by Goofych** [erri120/Playnite.Extensions#28]
**Describe the bug**
F95ZoneMetadata fails to detect community score.

**To Reproduce**

Download Metadata -> F95zone 

there the error) -> Community score field stays unchecked, no score filled in..

**Expected behavior**
Expected to see "4.5 start(s)" converted to 90 community score and put into "Community Score" field in Game Details Window.

**Versions**
latest

**Log file**
[playnite.log](https://github.com/erri120/Playnite.Extensions/files/5434616/playnite.log)

PS One of your own screenshots illustrating usage of f95zone plugin shows that same behavior. Please respond if I misunderstood how it supposed to work.

PPS Non of the games I tested it on were rated by me personally, but considering requirements for rating a game there I would say that's to be expected in most cases.

**Comment by erri120** [comment]
Can you link the game that fails?

**Comment by Goofych** [comment]
https://f95zone.to/threads/chloe-18-fake-family-v0-2-gds.56142/

I'm pretty sure its will fail on any game. I just now picked a random one from "trending" and it failed at filling score field..

PS Before, I was testing things before starting filling up my collection and noticed what none of them had score rating even though it's specifically mentioned in the readme here.

**Comment by erri120** [comment]
I just updated all extensions to the new SDK version, should also give you some more debug info in the log.
![26-10-2020 10-53-48](https://user-images.githubusercontent.com/16577545/97158356-36056a80-1771-11eb-9794-3e8e50ef4645.png)

**Comment by Goofych** [comment]
weird.
![2020-10-26_16-16-27](https://user-images.githubusercontent.com/73356695/97176964-c4e0aa00-17a6-11eb-82df-a8f7e82fa544.png)

and last lines in log:

`26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found 2 Labels for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found Name "Chloe 18 Fake Family [v0.2]" for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found 18 Genres for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found Release Date "2020-07-07T08:09:39+0100" for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Unable to parse rating "4.50"
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found 9 Images for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Found Description for chloe-18-fake-family-v0-2-gds.56142
26-10 16:15:45.219|DEBUG|Downloader:Downloading data from https://attachments.f95zone.to/2020/07/735019_735009_best_baner_ever.jpg to C:\Users\Goofy\AppData\Local\Temp\Playnite\temp_preview_cover.jpg.
26-10 16:16:01.934|DEBUG|Downloader:Downloading data from https://attachments.f95zone.to/2020/07/734768_734749_1594102900995.png to C:\Users\Goofy\AppData\Local\Temp\Playnite\temp_preview_background.png.`

[playnite.log](https://github.com/erri120/Playnite.Extensions/files/5438974/playnite.log)

seems like something gone wrong here: **26-10 16:15:33.927|DEBUG|F95ZoneMetadata:Unable to parse rating "4.50"**

**Comment by erri120** [comment]
I highly suspect this has something to do with your system culture where `4.50` can not be parsed because it expects `4,50`. What language is your Window Installation set to?

**Comment by Goofych** [comment]
Russian

**Comment by Goofych** [comment]
yeah, looks like you are correct. I just went and changed region to English (USA), restarted Playnite and it worked..

![2020-10-26_16-36-52](https://user-images.githubusercontent.com/73356695/97179123-83053300-17a9-11eb-9dc3-08164bd34ae0.png)

**Comment by erri120** [comment]
Fixed with e3a65dcf13065a369f509ed823e9ac52195273a8
