### ISSUE TITLE
ExtensionUpdaterPlugin showing erroneous message..

### ISSUE THREAD

**Issue by Goofych** [erri120/Playnite.Extensions#29]
that's msg:
![2020-10-26_18-47-45](https://user-images.githubusercontent.com/73356695/97206998-88bf4080-17ca-11eb-99f6-302f80425c46.png)

and that's in the logs:

> 26-10 20:30:29.357|INFO|PlayniteApplication:Shutting down Playnite
26-10 20:30:29.373|DEBUG|PlayniteApplication:Releasing Playnite resources...
26-10 20:30:31.982|INFO|PlayniteApplication:Application started from 'C:\Utils\Playnite', with '' arguments.
26-10 20:30:32.116|INFO|ExtensionFactory:Loaded plugin: DLSite Metadata Provider, version 1.7.1
26-10 20:30:32.116|INFO|DLSiteMetadata:Loaded 0 DLSite genres
26-10 20:30:32.116|INFO|ExtensionFactory:Loaded plugin: Extension Updater, version 1.7.1
26-10 20:30:32.116|INFO|ExtensionFactory:Loaded plugin: F95Zone Metadata Provider, version 1.7.1
26-10 20:30:32.127|INFO|ExtensionFactory:Loaded plugin: Humble Library Importer, version 1.0
26-10 20:30:32.127|INFO|ExtensionFactory:Loaded plugin: IGDB metadata provider, version 1.0
26-10 20:30:32.127|INFO|ExtensionFactory:Loaded plugin: Jastusa Metadata Provider, version 1.7.1
26-10 20:30:32.127|INFO|ExtensionFactory:Loaded plugin: PlayStation Library Importer, version 1.0
**26-10 20:30:32.147|INFO|ExtensionFactory:Loaded plugin: Screenshot Plugin, version 1.6.1**
26-10 20:30:32.147|INFO|ExtensionFactory:Loaded plugin: VNDB Metadata Provider, version 1.7.1
26-10 20:30:32.147|INFO|ExtensionFactory:Loaded plugin: Xbox Library Importer, version 1.0
26-10 20:30:32.336|INFO|ExtensionFactory:Loaded script extension: C:\Utils\Playnite\Extensions\LibraryExporter\LibraryExporter.ps1, version 1.0
26-10 20:30:32.713|INFO|GameDatabase:Opening db C:\Users\Goofy\AppData\Roaming\Playnite\library
26-10 20:30:32.771|DEBUG|ExecutionTimer:--- Timer 'DatabaseLoadCollections', 56 ms to complete.
26-10 20:30:32.771|INFO|DatabaseStats:Completely recalculating database statistics...
26-10 20:30:32.886|INFO|DesktopAppViewModel:Importing games from Humble plugin.
26-10 20:30:32.932|INFO|ExtensionUpdaterPlugin:Found: erri120/Playnite.Extensions
26-10 20:30:32.932|INFO|PlayniteApplication:Application 8.3.0.30821 started
26-10 20:30:32.932|INFO|DesktopAppViewModel:Importing games from PlayStation plugin.
26-10 20:30:32.945|INFO|VNDBMetadata:Tags cache contains 2587 tags
26-10 20:30:33.016|INFO|DesktopAppViewModel:Importing games from Xbox plugin.
26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:DLSite Metadata Provider is up-to-date
26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:Extension Updater is up-to-date
26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:F95Zone Metadata Provider is up-to-date
26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:Jastusa Metadata Provider is up-to-date
**26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:There is a new version for Screenshot Plugin: 1.7.1**
26-10 20:30:33.416|INFO|ExtensionUpdaterPlugin:VNDB Metadata Provider is up-to-date
26-10 20:30:37.932|DEBUG|Downloader:Downloading string content from http://www.playnite.link/update/stable/info.json using System.Text.UTF8Encoding encoding.

So, 1) Updater plugin tells me all of the extensions in Extensions package need updating even though there is only one non-up-to-date extension, and 2) there is a plugin in the latest release which version is behind latest release version.

**Comment by erri120** [comment]
The version of the Screenshot Plugin is not being updated correctly in my release pipeline which is now fixed. The message includes all plugins from this repository because they are grouped by repository so we don't end up checking the same repo 10 times, will fix this and #17 soon.

**Comment by erri120** [comment]
Fixed in c27f0067aa654c9979d582cd1af2387b391dc643
