### ISSUE TITLE
Error fetching metadata for Game

### ISSUE THREAD

**Issue by ThePharaohArt** [erri120/Playnite.Extensions#37]
**Describe the bug**
Unable to fetch metadata for any games using your latest extension versions.

**To Reproduce**
1. Select game to edit
2. pick any of your extensions, (latest version)
3. it then gives error that it cannot fetch for any game, see the screenshots
![image](https://user-images.githubusercontent.com/32932497/99127162-9e5ba500-25d5-11eb-9bda-f759f2668282.png)
![image](https://user-images.githubusercontent.com/32932497/99127186-addaee00-25d5-11eb-8b55-a6728e51b1ae.png)

**Versions**
- Playnite Version: 8.7
- Extension Version: 1.7.2

**Comment by erri120** [comment]
Tripple check the name of the game and the usage section in the readme of the extension you want to use.

**Comment by ThePharaohArt** [comment]
I'll check out the readme on github,

also doesn't work with your F95Zone
![image](https://user-images.githubusercontent.com/32932497/99130780-4a55be00-25df-11eb-8618-511453e09a99.png)

**Comment by ThePharaohArt** [comment]
> Tripple check the name of the game and the usage section in the readme of the extension you want to use.

Checked the readme. I'll delete the extension now, since this "bypass" that you're doing so not something I want to do with huge game list. I'll keep an eye on if the name issue changes at some point. Or if someone else does it better.

Thanks.

**Comment by erri120** [comment]
Btw this "bypass" is the only possible solution to get the exact game you want. If you would just slap the game name and try to find it using that, you'd have to hit up the website with a search which

1) might require a login
2) might give 0 or 1+ results
3) requires more requests, creating more traffic than necessary

All metadata extensions in this repo either use an API (like the VNDB one) or do static HTML parsing using HTMLAgilityPack.
