### ISSUE TITLE
Add settings for where parsed content is being placed

### ISSUE THREAD

**Issue by hellomynameisleo** [erri120/Playnite.Extensions#4]
much thanks for making the plugin!

Is it possible to change how the dlsite plugin places it in playnite's game details?
In dlsite's "english/japanese" website conterparts tags are labeled as "genre/tags", could there maybe be an option to put these tags to the tags section instead of genre within playnite since they're actually tags.
While the "Work Format/Categories" into the genre instead?

**Comment by erri120** [comment]
Will probably work on this when the SDK gets updated so Metadata Providers can fill in more information,
