### ISSUE TITLE
metadata providers don't work anymore!

### ISSUE THREAD

**Issue by shakeyourbunny** [erri120/Playnite.Extensions#40]
**Describe the bug**
Metadata providers bail out with an error message that the name does not start or something similar.

**To Reproduce**
1. Right-Click on a game and choose "edit metadata"
2. Choose "DLSite", "F95" or "Jastusa" as a metadata provider.
DLSite: Failed to download metadata. Root Letter (game name) does not start with "RJ/RE".
F95Zone: Failed to download.metadata. Name must not be empty.
Jastusa: Failed to download metadata. Name must start with https://www.justusa.com!

**Expected behavior**
Downloading metadata...

**Versions**
- Playnite Version: 8.11
- Extension Version: 1.7.2

**Log file**
03-01 18:44:30.133|ERROR|GameEditViewModel:Failed to download metadata, cb91dfc9-b977-43bf-8e70-55f46e410fab, 377680
System.Exception: Sakura Beach does not start with RJ/RE!
   at DLSiteMetadata.DLSiteMetadataProvider.GetID() in D:\a\1\s\DLSiteMetadata\DLSiteMetadataProvider.cs:line 28
   at Extensions.Common.AMetadataProvider`1.get_ID() in D:\a\1\s\Extensions.Common\AMetadataProvider.cs:line 26
   at Extensions.Common.AMetadataProvider`1.get_AvailableFields() in D:\a\1\s\Extensions.Common\AMetadataProvider.cs:line 50
   at Extensions.Common.AMetadataProvider`1.GetName() in D:\a\1\s\Extensions.Common\AMetadataProvider.cs:line 82
   at Playnite.DesktopApp.ViewModels.GameEditViewModel.<>c__DisplayClass470_0.<DownloadPluginData>b__0() in E:\Devel\Playnite\source\Playnite.DesktopApp\ViewModels\GameEditViewModelMetadata.cs:line 376

**Comment by erri120** [comment]
You need to provide the URL to the game on the site you want to grab the metadata from, from the README for DLSite:
> Copy either the entire URL or just the ID (eg RE234198 or RJ173356) into the Name field, click the Download Metadata... button in the bottom left corner and select DLSite.

Only providing the name will fail.

**Comment by shakeyourbunny** [comment]
So, this is really a pointless extension, especially you have actively lookup the URL or this ID and then let the extension download the data?

I was under the impression that exactly this is the job of  the extension itself? What a lazy coding.

**Comment by ThePharaohArt** [comment]
> So, this is really a pointless extension, especially you have actively lookup the URL or this ID and then let the extension download the data?
> 
> I was under the impression that exactly this is the job of the extension itself? What a lazy coding.

I reported this earlier in 2020 see here [https://github.com/erri120/Playnite.Extensions/issues/37](Issue37)
