### ISSUE TITLE
DSLITE metadata provider plugin can add "NULL" website links which can make playnite crash

### ISSUE THREAD

**Issue by joyrider3774** [erri120/Playnite.Extensions#67]
**Describe the bug**
With certain games for example this one :
https://store.steampowered.com/app/1170130/Restrictr/ or https://store.steampowered.com/app/844060/Reality_Blender/ the dslite metadata provider will add "null" website links which playnite does not like and will crash upon when trying to remove such links.

**To Reproduce**
1. add any of the free games above to steam
2. update library for steam
3. download metadata using DSLITE plugin
4. see it will add a 2nd empty website url
5. try to remove this links from playnite
6. playnite crashes

**Expected behavior**
Plugin to not add empty / null links to playnite's game database

**Screenshots**

https://user-images.githubusercontent.com/10714776/128618117-9dadffc3-1a54-4a8e-8420-a0a8860a8566.mp4

**Versions**
- Playnite Version: Latest playnite version
- Extension Version: DSLITE latest release

**Comment by erri120** [comment]
I've paused development on this project as I'm waiting for Playnite to switch to .NET 5 or .NET 6. It is currently using .NET Framework 4.6.x which is like 5 or 6 years old and writing code for it is a pain when I'm writing modern code every other day.
