### ISSUE TITLE
More, some requests if possible [F95Zone]

### ISSUE THREAD

**Issue by Drakses** [erri120/Playnite.Extensions#71]
**Describe the bug**
1. Till I fond this extension, I added games manually. All my games have the tags on `Tags` section, play type (Sandbox, Visual Novel etc) on `Genres` section and game engine (Ren'py, RPGM etc) on `Categories` section.
2. Also I'm adding on each game screenshots in description.
3.  Version appears in Name not in Version field. 

**Expected behavior**
1. It will be nice to have a way so you can choose or modify which goes where. An extension settings (if possible) where you chose the source data and the destination field. A function that compare for each existing tags == extracted tags and if they match exclude the extracted tag else add it. This way we avoid duplicates. 
2. This I achieved with an simple HTML template in description. It will be great if we can add them to description because the extension is already extract them. :)  
   `<center><div><img src="image link"></div></center>`
Added some examples of how I customize them below.
3. I saw that the name format is `game name[version]`. If we can remove the version from the `Name` and add it to `Version` field will be awesome. 

**Screenshots**

![image](https://user-images.githubusercontent.com/46842179/132071799-ca34426f-f55e-4eb7-b7bd-2658bc59bf26.png)

![image](https://user-images.githubusercontent.com/46842179/132072927-849a2012-f560-4f33-a6a9-a351f547cba7.png)

![image](https://user-images.githubusercontent.com/46842179/132073175-397b1aa4-faf4-40c8-9c77-7a20ffbc5e8c.png)

**Versions**
- Playnite Version: 8.14
- Extension Version: 1.7.2

Thank you!

**Comment by erri120** [comment]
See #72
