### ISSUE TITLE
Game Management: Setting to keep the game size stored even after it's uninstalled

### ISSUE THREAD

**Issue by Plagued0** [erri120/Playnite.Extensions#93]
If this is out of the project's scope then i apologize in advance

I really like how this extension works out as i can easily see the space taken by MBs and GBs aswell as a clean rounding, but there's only one thing i dislike which is the fact this data gets removed as soon as you uninstall a game

I'd love if i could keep this data visible, maybe throught some setting to not auto-remove data in extension settings, or even a checkbox to hide uninstalled games in "View Storage Statistics" tab.

**Comment by erri120** [comment]
See #94
