### ISSUE TITLE
Game Management: Size visibility on Details View

### ISSUE THREAD

**Issue by Plagued0** [erri120/Playnite.Extensions#94]
I believe it would be really handy if there was some binding to show the size somewhere on details panel, rather than only on the plugin's sidebar button. I think it would work great if it was possible to make it visible on the other views throught theme editing, Steam has something similar
![image](https://user-images.githubusercontent.com/93556871/168482158-5ecf48e2-f054-422d-a435-83c75f0c1b89.png)

**Comment by erri120** [comment]
Some notes:
1) I don't know really know if an extension can modify the views
2) Steam only shows this for games that are not installed, I guess this goes hand in hand with #93 but the extension simply enumerates all files and sums up the file sizes so we don't know how big the game is when it's not installed
3) The [Games Size Calculator](https://playnite.link/addons.html#GamesSizeCalculator_97cc59db-3f80-4852-8bfc-a80304f9efe9) extension by [darklinkpower](https://github.com/darklinkpower) does something similar but puts the size in the Version field

I'm planning on integrating the Game Management extension in Playnite itself, similar to the now obsolete [ExtensionUpdater](https://github.com/erri120/Playnite.Extensions/tree/pre-rework/ExtensionUpdater) I created a while back. I'll put this issue on hold, I suggest subscribing to https://github.com/JosefNemec/Playnite/issues/167 and https://github.com/JosefNemec/Playnite/issues/2504 and wait till Playnite has something similar.

**Comment by Plagued0** [comment]
For the first note, i meant something similar to news viewer and successstory, but anyways thank you very much for the quick response :)

My only grip with Game Size Calculator is that it's done in a way it's possible to order by size so it will use decimals and never use "MB", but it's a great workaround for visibility on other areas
